[package]
name = "aluvm"
description = "Functional registry-based RISC virtual machine"
version = "0.11.0"
authors = ["Dr Maxim Orlovsky <orlovsky@ubideco.org>"]
repository = "https://github.com/aluvm/rust-aluvm"
homepage = "https://aluvm.org"
keywords = ["virtual-machine", "emulator", "functional", "risc", "edge-computing"]
categories = ["no-std", "embedded", "compilers", "cryptography", "emulators"]
rust-version = "1.81.0"
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
exclude = [".github"]

[lib]
name = "aluvm"

[[bin]]
name = "aluvm-stl"
required-features = ["stl"]

[dependencies]
amplify = { version = "~4.8.0", default-features = false, features = ["apfloat", "derive", "hex"] }
ascii-armor = { version = "0.9.0", optional = true }
baid64 = "0.4.1"
paste = "1"
strict_encoding = { version = "~2.8.2", default-features = false, features = ["float", "derive"] }
strict_types = { version = "~2.8.3", optional = true }
sha2 = "0.10.8"
blake3 = "1.5.4"
ripemd = "0.1.3"
secp256k1 = { version = "0.30.0", optional = true, features = ["global-context"] }
curve25519-dalek = { version = "4.1.3", optional = true }
half = "2.4.1" # Required to maintain MSRV
serde_crate = { package = "serde", version = "1", optional = true }

[features]
default = ["std"]
all = ["stl", "std", "log", "secp256k1", "curve25519", "serde", "ascii-armor"]
stl = ["strict_types/armor", "std"]
std = ["amplify/std"]
log = ["std"]
alloc = ["amplify/alloc"]
curve25519 = ["curve25519-dalek"]
serde = ["serde_crate", "amplify/serde", "std", "strict_encoding/serde"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
rand = { version = "0.9.1", optional = true }
getrandom = { version = "0.3", features = ["wasm_js"] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3"

[package.metadata.docs.rs]
features = ["all"]
