[package]
name = "aluvm"
description = "Functional registry-based RISC virtual machine"
version = "0.12.0-alpha.1"
authors = ["Dr Maxim Orlovsky <orlovsky@ubideco.org>"]
repository = "https://github.com/aluvm/rust-aluvm"
homepage = "https://aluvm.org"
keywords = ["virtual-machine", "emulator", "functional", "risc", "edge-computing"]
categories = ["no-std", "embedded", "compilers", "cryptography", "emulators"]
rust-version = "1.77.0"
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
exclude = [".github"]

[lib]
name = "aluvm"

[[bin]]
name = "aluvm-stl"
required-features = ["stl"]

[dependencies]
amplify = "4.7.0"
ascii-armor = { version = "0.7.2", optional = true }
baid64 = "0.2.2"
commit_verify = "0.11.0-beta.8"
paste = "1"
strict_encoding = { version = "2.7.0", default-features = false, features = ["float", "derive"] }
strict_types = { version = "2.7.1", optional = true }
serde = { version = "1", optional = true }

[features]
default = []
all = [
    "stl", "log", "armor",
    # Instruction set architecture extensions
    # "a1024", "array", "str", "float", "sha", "secp256k1", "curve25519",
    "serde"
]

armor = ["dep:ascii-armor"]
stl = ["strict_types/armor"]
log = []
alloc = ["amplify/alloc"]
serde = ["dep:serde", "amplify/serde", "strict_encoding/serde"]

# Instruction set architecture extensions
# a1024 = []
# array = []
# str = []
# float = ["amplify/apfloat", "half"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
rand = { version = "0.8.4", optional = true }
getrandom = { version = "0.2", features = ["js"] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3"

[package.metadata.docs.rs]
features = ["all"]
